### ISSUE TITLE
hey whitj00

### ISSUE THREAD

**Issue by doged** [whitj00/cryptosmsbot#1]
wasnt sure how to get a hold of you another way, i had a quick question.. on the iphone/ios doge wallet, the one that uses ssh..

im having one error trying to build, xcode is telling me it cant find NMSSH.h in the senddogecontroller.h file.  anu suggestions? did you also come across this error? ive tried to contact slayter but have not heard back yet.

**Comment by whitj00** [comment]
Sorry, I never figured that out either
